"""empty message

Revision ID: 443b67e7b2db
Revises: f603c87fdefe
Create Date: 2019-10-10 16:35:29.432000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '443b67e7b2db'
down_revision = 'f603c87fdefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=200), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
