"""empty message

Revision ID: d48278dd8292
Revises: 443b67e7b2db
Create Date: 2019-10-10 16:37:54.224000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd48278dd8292'
down_revision = '443b67e7b2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=200), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
